# run hellow world script
name: Hello World CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World script
        run: echo "Hello, World!" 